# aqui tenho que colocar o nome do pipeline (fluxo de trabalho - workflow)
name: Primeiro Workflow
# em quais eventos de gatilho quero que dispare meu script 
on: 
  push: 
   branches:
     - developer
     - main
     - master
  pull_request:
   branches: [main, master]
    
jobs:
  Primeiro-Fluxo:
    # esté é o nome do fluxo de trabalho
    name: Job1
    # para ser executado nesta maquina virtual linux
    runs-on: ubuntu-latest
    # agora irei incluir os passos do script 
    steps: 
      - name: Passo 1
        run: echo "Executando o primeiro passo."
      - name: Passo 2
        run: echo "Executando o segundo passo."
      - name: Passo 3
        run: echo "Executando o terceiro passo."
    
  Segundo-Fluxo:
    # esté é o nome do fluxo de trabalho
      name: Job2
    # para ser executado nesta maquina virtual linux
      runs-on: ubuntu-latest
    # agora irei incluir os passos do script 
      steps: 
       - name: Passo 4
         run: echo "Executando o quarto passo."
       - name: Passo 5
         run: echo "Executando o quinto passo."
       - name: Passo 6
         run: echo "Executando o sexto passo."   

  Terceiro-Fluxo:
    # esté é o nome do fluxo de trabalho
    name: Job3
    # para ser executado nesta maquina virtual linux
    runs-on: ubuntu-latest
    # agora irei incluir os passos do script 
    steps: 
      - name: Passo 7
        run: echo "Executando o setimo passo."
      - name: Passo 8
        run: echo "Executando o oitavo passo."
      - name: Passo 9
        run: echo "Executando o nono passo."
  
